### ISSUE TITLE
Network auth error

### ISSUE THREAD

**Issue by JoseHidalgo** [3dyd/acfu#10]
Hi, and thanks for the component.
I can't make it work right now. Here's the error :
`The following errors occurred during the checking for updates:
Spider Monkey Panel: Network authentication error (80090302)
Auto Check for Updates: Network authentication error (80090302)
JScript Panel: Network authentication error (80090302)`
I have a valid GitHub auth token, at the right place in foobar prefs.
Also, how do I make the UI element appear under DUI, right next to my menus ?
Thanks.

**Comment by 3dyd** [comment]
Hi,
Take a look at foo_youtube thread starting with [this comment](https://hydrogenaud.io/index.php/topic,104379.1000.html). There was discussion about the same problem (Network authentication error) happening on Windows 7 and proposed solution did the trick.

> how do I make the UI element appear under DUI, right next to my menus ?

Unfortunately this is only possible in CUI.

By current foobar2000 API and DUI design that UI area in DUI cannot contain custom UI elements.

Custom toolar button (i.e. not entire UIE but just a button) also won't work because there are no way for component to change its icon, and without this it would be useless.

**Comment by JoseHidalgo** [comment]
Thanks ! The "Easy Fix + Win 7 Update" did the trick indeed. Problem solved !

**Comment by 3dyd** [comment]
(for future reference)

TLS 1.1 and 1.2 need to be enabled by default on Windows 7:
[Update to enable TLS 1.1 and TLS 1.2 as default secure protocols in WinHTTP in Windows](https://support.microsoft.com/en-us/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-wi)
